### ISSUE TITLE
Native Library libhfscompressor already loaded in another classloader

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-gradle-plugin#55]
Getting this when using the 2.6 daemon now:

```
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/badlogic/.m2/repository/org/robovm/robovm-dist/1.8.1-SNAPSHOT/unpacked/robovm-1.8.1-SNAPSHOT/bin/libhfscompressor.dylib already loaded in another classloader
	at org.robovm.compiler.util.io.HfsCompressor.loadLib(HfsCompressor.java:43)
	at org.robovm.compiler.util.io.HfsCompressor.compress(HfsCompressor.java:60)
	at org.robovm.compiler.ClassCompiler.generateMachineCode(ClassCompiler.java:438)
	at org.robovm.compiler.ClassCompiler.access$000(ClassCompiler.java:139)
	at org.robovm.compiler.ClassCompiler$1.run(ClassCompiler.java:336)
```

**Comment by badlogic** [comment]
Catching the UnsatisfiedLinkError in the HfsCompressor initializer fixes this issue.
